// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CheckReportStatus.
const (
	CheckReportStatusCompleted CheckReportStatus = "completed"
	CheckReportStatusDisabled  CheckReportStatus = "disabled"
	CheckReportStatusError     CheckReportStatus = "error"
	CheckReportStatusFail      CheckReportStatus = "fail"
	CheckReportStatusPass      CheckReportStatus = "pass"
	CheckReportStatusSkipped   CheckReportStatus = "skipped"
	CheckReportStatusUnknown   CheckReportStatus = "unknown"
)

// Defines values for HealthStatus.
const (
	Healthy   HealthStatus = "healthy"
	Unhealthy HealthStatus = "unhealthy"
)

// Defines values for GetComponentReportsParamsStatus.
const (
	GetComponentReportsParamsStatusCompleted GetComponentReportsParamsStatus = "completed"
	GetComponentReportsParamsStatusDisabled  GetComponentReportsParamsStatus = "disabled"
	GetComponentReportsParamsStatusError     GetComponentReportsParamsStatus = "error"
	GetComponentReportsParamsStatusFail      GetComponentReportsParamsStatus = "fail"
	GetComponentReportsParamsStatusPass      GetComponentReportsParamsStatus = "pass"
	GetComponentReportsParamsStatusSkipped   GetComponentReportsParamsStatus = "skipped"
	GetComponentReportsParamsStatusUnknown   GetComponentReportsParamsStatus = "unknown"
)

// CheckReport A quality check report for a component
type CheckReport struct {
	// CheckSlug Unique identifier for the check type
	CheckSlug string `json:"check_slug"`

	// Id Unique identifier for the report
	Id string `json:"id"`

	// Status Status of the check execution
	Status CheckReportStatus `json:"status"`

	// Timestamp When the check was executed
	Timestamp time.Time `json:"timestamp"`
}

// CheckReportStatus Status of the check execution
type CheckReportStatus string

// Component A component discovered from a source
type Component struct {
	// Description Additional context about the component's purpose and functionality
	Description *string `json:"description,omitempty"`

	// Id Unique identifier for the component. If not provided, the name will be used as the identifier.
	Id *string `json:"id,omitempty"`

	// Name Human-readable name of the component
	Name string `json:"name"`

	// Owners Ownership information for a component
	Owners *Owners `json:"owners,omitempty"`
}

// ComponentReportsResponse Response containing component reports with pagination
type ComponentReportsResponse struct {
	// Pagination Pagination metadata for list responses
	Pagination Pagination `json:"pagination"`

	// Reports List of check reports for the component
	Reports []CheckReport `json:"reports"`
}

// Error Error response
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Error Error message
	Error string `json:"error"`
}

// Health Health status of the service
type Health struct {
	// Status Health status
	Status HealthStatus `json:"status"`

	// Timestamp Timestamp of the health check
	Timestamp time.Time `json:"timestamp"`
}

// HealthStatus Health status
type HealthStatus string

// Owners Ownership information for a component
type Owners struct {
	// Maintainers List of user identifiers responsible for maintaining this component
	Maintainers *[]string `json:"maintainers,omitempty"`

	// Team Team responsible for owning this component
	Team *string `json:"team,omitempty"`
}

// Pagination Pagination metadata for list responses
type Pagination struct {
	// HasMore Whether there are more items available
	HasMore bool `json:"has_more"`

	// Limit Number of items returned in this response
	Limit int `json:"limit"`

	// Offset Offset used for this response
	Offset int `json:"offset"`

	// Total Total number of items available
	Total int `json:"total"`
}

// GetComponentReportsParams defines parameters for GetComponentReports.
type GetComponentReportsParams struct {
	// Status Filter by check status
	Status *GetComponentReportsParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// CheckSlug Filter by specific check type
	CheckSlug *string `form:"check_slug,omitempty" json:"check_slug,omitempty"`

	// Since Filter reports since timestamp (ISO 8601)
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`

	// Limit Number of reports to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Pagination offset
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// LatestPerCheck Return only the latest report for each check type
	LatestPerCheck *bool `form:"latest_per_check,omitempty" json:"latest_per_check,omitempty"`
}

// GetComponentReportsParamsStatus defines parameters for GetComponentReports.
type GetComponentReportsParamsStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all components
	// (GET /components)
	GetComponents(w http.ResponseWriter, r *http.Request)
	// Get component by ID
	// (GET /components/{componentId})
	GetComponentById(w http.ResponseWriter, r *http.Request, componentId string)
	// Get reports for component
	// (GET /components/{componentId}/reports)
	GetComponentReports(w http.ResponseWriter, r *http.Request, componentId string, params GetComponentReportsParams)
	// Health check
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get all components
// (GET /components)
func (_ Unimplemented) GetComponents(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get component by ID
// (GET /components/{componentId})
func (_ Unimplemented) GetComponentById(w http.ResponseWriter, r *http.Request, componentId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get reports for component
// (GET /components/{componentId}/reports)
func (_ Unimplemented) GetComponentReports(w http.ResponseWriter, r *http.Request, componentId string, params GetComponentReportsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetComponents operation middleware
func (siw *ServerInterfaceWrapper) GetComponents(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetComponents(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetComponentById operation middleware
func (siw *ServerInterfaceWrapper) GetComponentById(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "componentId" -------------
	var componentId string

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", chi.URLParam(r, "componentId"), &componentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "componentId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetComponentById(w, r, componentId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetComponentReports operation middleware
func (siw *ServerInterfaceWrapper) GetComponentReports(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "componentId" -------------
	var componentId string

	err = runtime.BindStyledParameterWithOptions("simple", "componentId", chi.URLParam(r, "componentId"), &componentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "componentId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetComponentReportsParams

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "check_slug" -------------

	err = runtime.BindQueryParameter("form", true, false, "check_slug", r.URL.Query(), &params.CheckSlug)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "check_slug", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	// ------------- Optional query parameter "latest_per_check" -------------

	err = runtime.BindQueryParameter("form", true, false, "latest_per_check", r.URL.Query(), &params.LatestPerCheck)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "latest_per_check", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetComponentReports(w, r, componentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/components", wrapper.GetComponents)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/components/{componentId}", wrapper.GetComponentById)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/components/{componentId}/reports", wrapper.GetComponentReports)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYf2/bNhP+KgTfF3jfAXIiJ07W+a9mWbcYKJrAzTBgRRGcpZPFViIVkkriBv7uA0n9",
	"Fu0k6DpswP6TROru4d3Du4d8pJHIC8GRa0Xnj1RFKeZgH89TjD4vsRBSm9cYVSRZoZngdE7PyG0JGdMb",
	"EplpRNp5JBGSAGlM0oAWUhQoNUNr006+UVm5Hpv8lbPbEgmLkWuWMJTWmk6xcqE3BdKA4gPkRYZ0TkvO",
	"9ESj0ooG1I7OqdKS8TXdBpTFL3Hh8PfMn5yE+GoWhhM8+mE1mU3j2QS+n55OZrPT05OT2SwMw9DnWGnQ",
	"pRo7f2+/E5F01oQPGJV2PKDIy5zOP9AClFlQAiyjAY2ZglWGMQ2o+syKwj6V/DMX9/YnKYWkgc1ihhpj",
	"+rG7hsrWCKNmOSoNeTGG+VuKvIPwHlSF0npuTR+FR7NJOJ1MT66n4fw4nIfh7wa2kDloOqcxaJwYP2P/",
	"24BKvC2ZxNgsmBnDHWY0Iezi/NhYEatPGGmzivOGZx5+NiQkMVORuEOJMUmkyAkQJUoZ4YidPRMji3HM",
	"zCNkJBJc44MmsBKldrGqnf1PkaKUhVBIgMckKXnkfmJ60wvfBfA4Q0VKhZJAqVNDyQjMZPun+SQk+wIV",
	"O76S3w3AA7JICBeaFFLcsRjjwI5zyJHcsywjKzSYYgLKDrS2Dnr4Db6JQnnHIvTBMwbHAC/KHPhEIsSG",
	"1M5rvSE6RaN1c9aPzPvdDsU9R2nT+F+JCZ3T/xy2pe2wqmuHl27WkIIW7V6KuUKolqgKwZVnafWIZQcw",
	"zvi6w0FXXxS5ZzolBawZrxPbp2Bn6ImVXLUz7WKs/TGst0xpE+JumVZjWtCAMo35k/HrNoVtEy+QEjaj",
	"oNaYgu6qfEF+Y4vYCLr9TGQd8VEvETHu+smOdXm0eHf9Zvnu7O3Nm+XycunjD+4DkaNSsB6Y5BqlKQdm",
	"F6AkdSneX+zcLF8ULhAynXr2jP1OVK99tDuvH5RdzadnpNNsUvt9Y3tK/dzrIO2ElzSR63qoxuvMOBYO",
	"28jxZHo0CaemjYRf0Uae2TQumzrRh+y+p6wgjDvvpuA8JWhyYHa3e03We8/W+LaQqprTzNRA46G2YmqG",
	"TpnyF8MPFDIW4WszCHxzEImcBvT1Sqwma6bTcmXW2+zicbp6ezWgGiH3ZA4hH+ET909Ao1cZaBM1Yv73",
	"pmqUiKteqeujaMdIjhpi0GCBZCaidUVQo2ykoG5yIdGranSKtuhJJCCRmHnERovAHbDMNKTukrQssUG9",
	"EiJDsJU2YznzCI53Zb5CabLtbErUpeQYE8Zd3Dp1rPFxEjYeGNe4Rmk7WZIo9Li4tN9dd3YFfIdZr1Ut",
	"NGSefJvPhA/QeyMy9cEdbELnpY5Ss5agTc14TxobZs95NNfVotof3BBibZVRLed6DVY5aXcHkolSVQLP",
	"FQPthIRcl4qcXS1oQO9QKucgPJgehDbmBXIoGJ3T44Pw4Nj2LJ1aUh32T0hrX2qWqCXDOyTgKCoSAlnW",
	"hTcUoZHgCVuX5r0Fa7hsWb+I6Zz+gvq8dW3iXPN+/kiPwtA1Qa4rAQxFkVU66fCTcrvKtW3z9Lzu3uzt",
	"cW/fBruURYtxG9CTF+LaB8fpAo9rf+s181SZ5yA3LnqDHNgJXT+PzfMi3j4nt6rAiCUs6gi71YYwrUg5",
	"VN57s/njZhFbiknIUdve8eFpLb9XKA/0OOP29KdTWktx2lks7W5aV+jajAxL98evZN4zCTfO8nl7gkMN",
	"LLP8moWzb8+v1rM5KSWi5PHfjts9Ci5+2k/uw875YD/Jfdc6qpJBY/rvZfmyo///CUQPhsh+ZplGaeLr",
	"otGq5+EFi0VxW6LctDCa2a3HP++K5wXY26w94xrNt5D+1cyLw1dzSDEeIWnEOfn/4v0leXUaTr/z3iuF",
	"0+uwcyDwRthY7GF63rFht3arsWpRCbihWvPBqLVOCyOHB5abVE/DMKA549WbTz7tkb6NeOoqOx+CZmIL",
	"IcYEykzbXxoA4XMALO3CieDZxm7DDAw5uje8CFG6g01uj3mjZM3cFChv6lPgiEuNzP5rms7wTmdvJ6gr",
	"6L89qO1B3fYQdVp5QA/dgf/LzoZz7ujTXg307zecUB/1luqO5BuSo/LgCUp190iYIvWlSD8iF907ju12",
	"u/0jAAD//0/nrrZdGQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
