openapi: 3.0.3
info:
  title: Argus API
  version: 0.1.0
paths:
  /components:
    get:
      summary: Get component manifest
      operationId: getComponents
      responses:
        "200":
          description: List of components
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Component"
components:
  schemas:
    Component:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
