// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for ReportSubmissionStatus.
const (
	ReportSubmissionStatusCompleted ReportSubmissionStatus = "completed"
	ReportSubmissionStatusDisabled  ReportSubmissionStatus = "disabled"
	ReportSubmissionStatusError     ReportSubmissionStatus = "error"
	ReportSubmissionStatusFail      ReportSubmissionStatus = "fail"
	ReportSubmissionStatusPass      ReportSubmissionStatus = "pass"
	ReportSubmissionStatusSkipped   ReportSubmissionStatus = "skipped"
	ReportSubmissionStatusUnknown   ReportSubmissionStatus = "unknown"
)

// Check Information about the check being reported
type Check struct {
	// Description Description of what the check does
	Description *string `json:"description,omitempty"`

	// Name Human-readable name for the check
	Name *string `json:"name,omitempty"`

	// Slug Unique identifier for the check type (e.g., "unit-tests", "build", "linter")
	Slug string `json:"slug"`
}

// Error Error response
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message
	Error *string `json:"error,omitempty"`
}

// ReportSubmission A quality check report submission
type ReportSubmission struct {
	// Check Information about the check being reported
	Check Check `json:"check"`

	// ComponentId Unique identifier of the component being reported on
	ComponentId string `json:"component_id"`

	// Details Check-specific data (coverage %, warnings, etc.)
	Details *map[string]interface{} `json:"details,omitempty"`

	// Metadata Execution context (CI job, environment, duration)
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Status Status of the check execution
	Status ReportSubmissionStatus `json:"status"`

	// Timestamp When the check was executed
	Timestamp time.Time `json:"timestamp"`
}

// ReportSubmissionStatus Status of the check execution
type ReportSubmissionStatus string

// ReportSubmissionResponse Response to a successful report submission
type ReportSubmissionResponse struct {
	// Message Success message
	Message *string `json:"message,omitempty"`

	// ReportId Unique identifier for the submitted report
	ReportId *string `json:"report_id,omitempty"`

	// Timestamp When the report was received
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// SubmitReportJSONRequestBody defines body for SubmitReport for application/json ContentType.
type SubmitReportJSONRequestBody = ReportSubmission

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a quality check report
	// (POST /reports/v1/reports)
	SubmitReport(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Submit a quality check report
// (POST /reports/v1/reports)
func (_ Unimplemented) SubmitReport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubmitReport operation middleware
func (siw *ServerInterfaceWrapper) SubmitReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reports/v1/reports", wrapper.SubmitReport)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXbW/bthb+KwTvvUALyA7lWLmdvqUvwAwUa+GmG7C1ECjq2GYqkSpJOcmC/PfhUK+2",
	"tMYpun2TafKc57w9D3lPhS5KrUA5S+N7asUOCu4/X+1AfMGPDKwwsnRSKxrTldpoU3D8RXiqK0fcDojA",
	"zSQFqbbEQKmNg4wGtDS6BOMk2JGhY7uv+19Eb8jNjg8tZxosDSjc8qLMgcZ0XSlLKiUdcWCdJRtt6u1t",
	"ODSgBb99C2rrdjQOGWMBdXclnrXOSLWlDwFVvIAxlJ+rgquZAZ7xNAeCm3r7PitDJB8RxBWCOHS5iKIJ",
	"jzavtmOPH5X8WgGRGSgnNxLMoT+CZsgzmG/nAflEMeyZD/sTxd9pJfOs/sylcmA+0ecHEPsDo6wEtJCq",
	"+z0C/BBQA18raSCj8R81+s/dLp1eg3AY1htjtBnH5ZeJAVtqZWHUEEJn8HeH/H/DIH69fLt6fXm1evdL",
	"8ma9fremE9nNwHGZe9s8yyQa5Pn7gU9nKgiO/F12Owl4162Vgfd7aoBbv91XJMFMEGlJmx3CVUYEV0o7",
	"kgKBonR3iGiUKfhWpgqwlm8P436Cv6nyjQCs/Xh+qNJCWjs5ipfka8Vz6e6a7qsHmtj+yKiQLVf818CG",
	"xvQ/Zz2tnDWcclYTykPQU04is1NmQW8OR/uIZ4gH1CeMV243s2D2UsDESH6z37+zhXxoM1uCkBspSMYd",
	"J8+E3oPhWyD/C8gNN0qqrQ0IODF/ftha7cakBCNAOeyA+EU0jwKaVcZTbWJBaJVZGi+RVXCUkw2XOY4l",
	"axdKbi0uhBGbKnwBjiOyp4X25hZE5VlZaOXg1pFnr1bkWqcBAbWXRqsClAtIi/QottRwJXY0pgWXWCYh",
	"k2ud+sLTcHG+jKjvh0K6xO44Vi8V4eIcjfTWfYH4FiuExhtASZecwueFscmwreOuGusP/eDXu+bynd7Z",
	"9v6rAjkPs0oDitmmAc2kRVFAcbNfZFn6r0p9UfrGH/LTXbd4DiiCn4et2dgaNZ2TBVjHi3IM87cdqAHC",
	"G24blN5zb3rBFssZC2dhdBWy+JzFjP2OsL1Y05hm3MEM/dDHSL6VuIMx7fI4BPv5BHpZt+Q/iqz9hzhN",
	"OLGVEGDtpspP4JuWJ8dFra1MEul6YNYhb/Qu87upqtQ4TiSpVrB78/XxAwhRxODFkrEZLH5KZ8swW874",
	"/8OL2XJ5cRFFyyVjjH1vfzRZwwYxIEDuf2iDHNUZl6Ta6AnxeL/yuWjygEQ9pSZ1I7lBYSy5fL+iAd2D",
	"qWWJhnM2Zxi+LkHxUtKYns/ZHMmh5G7nO+GsMXe2D9tPXC61dVPdgZgIb3OFOPkRvI4C5uRqkFWZ56iz",
	"e55LTFRG0soRFF/rtIFsTj3Kmo9WWedr3fYADhhY91JndzXlK+eJ7Z7yssyl8AfPrm2tx03VfCj+dpc0",
	"zTS+N9Q7kcY48Vsnx8dWRcHNHY3pS7+nw7XneQUHEn5o32+3R/rLjZMbLvB8fYOut9H2eltjHkv9sTQP",
	"tbYxmVj5JyRFiio2XwRN9GMZDBcMz5egMlBCgk2ErjChy+hI6h5ToIsTFag0OqtEKw7TIhQuWK1Creh0",
	"jN8P8PEgRn4QcaDwmp6glJ9W7e7180jFuwfK6VU/5XXVVP7g+dOUf/DeeEoP/DP3oKf0wg+/jTyhD1jT",
	"B3jK35gfu0+PLvIPh0qOtzm/UMusT/GCsRPo5/v8d0rvcRxr/be09yGgyx8IrH6MTqBYKc/fpCFjf09H",
	"59G/49yBwUcm9j6Y+q3p574f1U6gpiQTjT78FQAA//9APFsasREAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
