// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// Defines values for ReportSubmissionStatus.
const (
	ReportSubmissionStatusCompleted ReportSubmissionStatus = "completed"
	ReportSubmissionStatusDisabled  ReportSubmissionStatus = "disabled"
	ReportSubmissionStatusError     ReportSubmissionStatus = "error"
	ReportSubmissionStatusFail      ReportSubmissionStatus = "fail"
	ReportSubmissionStatusPass      ReportSubmissionStatus = "pass"
	ReportSubmissionStatusSkipped   ReportSubmissionStatus = "skipped"
	ReportSubmissionStatusUnknown   ReportSubmissionStatus = "unknown"
)

// Check Information about the check being reported
type Check struct {
	// Description Description of what the check does
	Description *string `json:"description,omitempty"`

	// Name Human-readable name for the check
	Name *string `json:"name,omitempty"`

	// Slug Unique identifier for the check type (e.g., "unit-tests", "build", "linter")
	Slug string `json:"slug"`
}

// Error Error response
type Error struct {
	// Code Error code
	Code *string `json:"code,omitempty"`

	// Details Additional error details
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error Error message
	Error *string `json:"error,omitempty"`
}

// ReportSubmission A quality check report submission
type ReportSubmission struct {
	// Check Information about the check being reported
	Check Check `json:"check"`

	// ComponentId Unique identifier of the component being reported on
	ComponentId string `json:"component_id"`

	// Details Check-specific data (coverage %, warnings, etc.)
	Details *map[string]interface{} `json:"details,omitempty"`

	// Metadata Execution context (CI job, environment, duration)
	Metadata *map[string]interface{} `json:"metadata,omitempty"`

	// Status Status of the check execution
	Status ReportSubmissionStatus `json:"status"`

	// Timestamp When the check was executed
	Timestamp time.Time `json:"timestamp"`
}

// ReportSubmissionStatus Status of the check execution
type ReportSubmissionStatus string

// ReportSubmissionResponse Response to a successful report submission
type ReportSubmissionResponse struct {
	// Message Success message
	Message *string `json:"message,omitempty"`

	// ReportId Unique identifier for the submitted report
	ReportId *string `json:"report_id,omitempty"`

	// Timestamp When the report was received
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// SubmitReportJSONRequestBody defines body for SubmitReport for application/json ContentType.
type SubmitReportJSONRequestBody = ReportSubmission

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Submit a quality check report
	// (POST /reports)
	SubmitReport(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Submit a quality check report
// (POST /reports)
func (_ Unimplemented) SubmitReport(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// SubmitReport operation middleware
func (siw *ServerInterfaceWrapper) SubmitReport(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubmitReport(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/reports", wrapper.SubmitReport)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xXa2/buBL9K8Tce4EWkB3asXO7+pY+gDVQbAs33QV2WwgUNbaZSqRKUk6yQf77YqiH",
	"H9I2TtHdbxZNzpx5nUPegzRFaTRq7yC+Byc3WIjw89UG5Rf6kaGTVpVeGQ0xLPTK2ELQFxOpqTzzG2SS",
	"NrMUlV4zi6WxHjOIoLSmROsVup6hY7uvd1/MrNjNRuxbzgw6iABvRVHmCDEsK+1YpZVnHp13bGVsvb0N",
	"ByIoxO1b1Gu/gXjCOY/A35V01nmr9BoeItCiwD6Un6tC6JFFkYk0R0abdvZDVvaRfCQQVwTi0OV0Ph/w",
	"6PJq3ff4UauvFTKVofZqpdAe+mNkhj3D8XocsU9AYY9C2J+AvtNK5Vn9M1fao/0Ezw8g7g70shJBoXT3",
	"3QP8EIHFr5WymEH8R43+c7fLpNcoPYX1xlpj+3GFZWbRlUY77DWENBn+3aHw334Qv16+Xby+vFq8+yV5",
	"s1y+W8JAdjP0QuXBtsgyRQZF/n7Pp7cVRkf+LrudDIPr1sqe93uwKFzYHiqSUCaYcqzNDhM6Y1JobTxL",
	"kWFR+jtC1MsUfitTBTon1odxP8HfUPl6AJZhPD9UaaGcGxzFS/a1Ernyd0331QPN3O5Ir5AtV/zX4gpi",
	"+M/ZjlbOGk45qwnlIdpRTqKyU2bBrA5H+4hnWAC0S5io/Gbk0G6VxIGR/Ga/f2cLhdBGrkSpVkqyTHjB",
	"nkmzRSvWyP4XsRthtdJrFzH0cvz8sLXajUmJVqL21AHxi/l4HkFW2UC1iUNpdOYgnhGr0CgnK6FyGkve",
	"LpTCOVqYzPlQ4Qv0gpA9LbQ3tyirwMrSaI+3nj17tWDXJo0Y6q2yRheofcRapEexpVZouYEYCqGoTFIl",
	"1yYNhYfJ9Hw2h9APhfKJ2wiqXion03MysrMeCiTWVCEy3gBKuuQUIS+cD4btvPBVX3/gQ1jvmit0emc7",
	"+K8K4jzKKkRA2YYIMuVIFEjc3BdVluFXpb9ocxMOhemuWzxHEsHP+63Z2Oo1nVcFOi+Ksg/ztw3qPYQ3",
	"wjUog+ed6SmfzkZ8MprMryY8Pucx578T7CDWEEMmPI7IDzxG8q3EHYxpl8d9sJ9PoJdlS/69yNp/mDdM",
	"MFdJic6tqvwEvml5sl/U2sogkS73zHrijZ3L/G6oKjWOE0mqFeyd+fr4AYT5nOOLGecjnP6UjmaTbDYS",
	"/59cjGazi4v5fDbjnPPv7Y8ma9QgFiWq7Q9tkKM605LSKzMgHu8XIRdNHoioh9SkbiS/VxjHLt8vIIIt",
	"2lqWYDLmY07hmxK1KBXEcD7mYyKHUvhN6ISz1lx8D6VxfqglCAgTbYIInDjC1M39mF3tpVLlOYnrVuSK",
	"spOxtPKMFNd5YzEbQ4BWk9Ai63wt28LTVKHzL012V/O89oHN7kGUZa5kOHh27WoRbkoVQglXuqTpoP5l",
	"od5J3CVY2Do4M64qCmHvIIaXYU+HayvyCg90+9B+2O6ORFdYr1ZC0vn62lxvg/ZOW2Pu6/uxHu8LbGMy",
	"cepPTIqUpGs8jZro+9o3mXI6X6LOUEuFLpGmooTO5kf69pjsXJwoO6U1WSVbRRhWnsmU19LTKk1H87up",
	"PZ6+eZg+miK6myek36dVu3vyPFLx7lVyetVPeVI1lT948zTl33tkPKUH/pnLz1N64YdfQZ7QB7zpAzoV",
	"rsmPXaJ7t/eHQ/mmK1xYqLU1pHjK+Qn0833+O3kPOI4F/luC+xDB7AcCq1+gAygWOvA3a8g4XM7J+fzf",
	"ce7R0suSeh9t/cAMc78b1U6ghnSSjD78FQAA//8husLDphEAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
