# Example Argus Configuration
# Copy this file to config.yaml and modify as needed
#
# Configuration Priority (highest to lowest):
# 1. Environment variables (ARGUS_*)
# 2. Config file values
# 3. Default values
#
# Environment Variables:
# ARGUS_CONFIG_PATH=/path/to/config.yaml
# ARGUS_STORAGE_HOST=localhost
# ARGUS_STORAGE_PORT=5432
# ARGUS_STORAGE_USER=postgres
# ARGUS_STORAGE_PASSWORD=postgres
# ARGUS_STORAGE_DBNAME=argus
# ARGUS_STORAGE_SSLMODE=disable

# Storage Configuration
# Defaults: host=localhost, port=5432, user=postgres, password=postgres, dbname=argus, sslmode=disable
storage:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: argus
  sslmode: disable

# VCS & Filesystem Sync Configuration
# Remove or leave empty to disable sync (warning will be logged)
# Default: sources: [] (no sync sources)
sync:
  sources:
    # Git repository sources
    # Example Git repository source
    - type: git
      url: "https://github.com/your-org/platform-services"
      branch: "main"
      interval: "5m" # Minimum 10s for git sources

    # Monorepo with specific base path to save bandwidth
    # Only syncs the "services" subdirectory instead of entire repo
    - type: git
      url: "https://github.com/your-org/monorepo"
      branch: "main"
      interval: "10m"
      base_path: "services"

    # Another Git example with deeper base path
    - type: git
      url: "https://github.com/your-org/large-repo"
      branch: "develop"
      interval: "15m"
      base_path: "microservices/backend"

    # Filesystem sources
    # Local filesystem source - entire directory
    - type: filesystem
      path: "/opt/services"
      interval: "2m" # Minimum 1s for filesystem sources

    # Development environment - local project directory
    - type: filesystem
      path: "./local-services"
      interval: "30s" # Fast interval for development

# Examples of mixed scenarios:

# Git + Filesystem hybrid setup
# sync:
#   sources:
#     # Production services from Git
#     - type: git
#       url: "https://github.com/company/production-services"
#       branch: "main"
#       base_path: "services"
#       interval: "10m"
#
#     # Local development overrides
#     - type: filesystem
#       path: "/home/dev/local-services"
#       interval: "1m"
#
#     # Shared infrastructure from different Git repo
#     - type: git
#       url: "https://github.com/company/infrastructure"
#       branch: "stable"
#       base_path: "k8s/manifests"
#       interval: "30m"

# No sync sources configuration (sync will be disabled with warning):
# sync:
#   sources: []

# Minimal Configuration Examples:
#
# 1. Zero configuration (uses all defaults):
#    No config file needed - application will start with defaults
#
# 2. Environment-only configuration:
#    ARGUS_STORAGE_HOST=my-db-host
#    ARGUS_STORAGE_PASSWORD=my-secure-password
#    ARGUS_STORAGE_DBNAME=my-argus-db
#
# 3. Partial configuration (missing values use defaults):
# storage:
#   host: my-db-host
#   password: my-secure-password
#   # Other values will use defaults
#
# 4. Full configuration with environment overrides:
#    Environment variables will override config file values
#    ARGUS_STORAGE_PASSWORD=override-password
