# Example Argus Configuration
# Copy this file to config.yaml and modify as needed

storage:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: argus
  sslmode: disable

# VCS & Filesystem Sync Configuration
# Remove or leave empty to disable sync (warning will be logged)
sync:
  sources:
    # Git repository sources
    # Example Git repository source
    - type: git
      url: "https://github.com/your-org/platform-services"
      branch: "main"
      interval: "5m" # Minimum 10s for git sources

    # Monorepo with specific base path to save bandwidth
    # Only syncs the "services" subdirectory instead of entire repo
    - type: git
      url: "https://github.com/your-org/monorepo"
      branch: "main"
      interval: "10m"
      base_path: "services"

    # Another Git example with deeper base path
    - type: git
      url: "https://github.com/your-org/large-repo"
      branch: "develop"
      interval: "15m"
      base_path: "microservices/backend"

    # Filesystem sources
    # Local filesystem source - entire directory
    - type: filesystem
      path: "/opt/services"
      interval: "2m" # Minimum 1s for filesystem sources

    # Local filesystem with base path optimization
    # Only syncs manifests from the "production" subdirectory
    - type: filesystem
      path: "/opt/deployments"
      base_path: "production"
      interval: "5m"

    # Development environment - local project directory
    - type: filesystem
      path: "./local-services"
      base_path: "active"
      interval: "30s" # Fast interval for development

# Examples of mixed scenarios:

# Git + Filesystem hybrid setup
# sync:
#   sources:
#     # Production services from Git
#     - type: git
#       url: "https://github.com/company/production-services"
#       branch: "main"
#       base_path: "services"
#       interval: "10m"
#
#     # Local development overrides
#     - type: filesystem
#       path: "/home/dev/local-services"
#       interval: "1m"
#
#     # Shared infrastructure from different Git repo
#     - type: git
#       url: "https://github.com/company/infrastructure"
#       branch: "stable"
#       base_path: "k8s/manifests"
#       interval: "30m"

# No sync sources configuration (sync will be disabled with warning):
# sync:
#   sources: []
