version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: argus-postgres
    environment:
      POSTGRES_DB: argus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d argus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - argus-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: argus-backend
    ports:
      - "8080:8080"
    environment:
      - ARGUS_CONFIG_PATH=config.yaml
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - argus-network

volumes:
  postgres_data:

networks:
  argus-network:
    driver: bridge
