version: 2

run:
  timeout: 5m
  go: "1.24.2"
  skip-dirs:
    - frontend

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - misspell
    - gosec
    - cyclop
    - dupl
    - goconst
    - gocritic

linters-settings:
  cyclop:
    max-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - cyclop
        - dupl
        - goconst
  max-issues-per-linter: 0
  max-same-issues: 0
