version: 2

run:
  timeout: 5m
  go: "1.24.2"
  # Focus only on the current directory (backend)
  # This prevents analyzing the frontend directory
  relative-path-mode: cfg

linters:
  disable-all: true
  enable:
    - bodyclose
    - copyloopvar
    - cyclop
    - dupl
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

linters-settings:
  # Exclude the frontend directory from analysis
  # This prevents the "could not load export data" error
  exclude:
    - "frontend/.*"
    - "../frontend/.*"

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0
  # Maximum count of issues with the same text
  max-same-issues: 0
  # Make issues output unique by line
  uniq-by-line: true
