name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Setup Volta
        uses: volta-cli/action@v4.2.1

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install frontend dependencies
        run: |
          cd frontend && bun install

      - name: Install Playwright
        run: |
          cd frontend && bunx playwright install chromium

      - name: Run backend tests
        run: |
          make backend/test

      - name: Start services for E2E tests
        run: |
          docker compose up -d --wait

      - name: Run E2E tests with seed data
        run: |
          docker compose up -d --wait
          ARGUS_BASE_URL=http://localhost:8080 bun ./frontend/scripts/report-seeder.ts --all-statuses --reports-per-component 5
          cd frontend && CI=true bun run test:e2e --reporter=list

  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          make docker/build-backend
          echo "Docker image built successfully"
