name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  GO_VERSION: "1.24.2"
  CGO_ENABLED: 0

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Install tools
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.3.0
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

      - name: Check generated code and dependencies
        run: |
          make backend/gen-all-and-diff

      - name: Run linters
        run: |
          make backend/lint

      - name: Run tests
        run: |
          make backend/test

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Build binary
        run: |
          make backend/build
